# Generated by Django 5.2.7 on 2025-10-29 11:54

import cinemaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(validators=[cinemaapp.models.verf_year])),
                ('duration', models.IntegerField(validators=[cinemaapp.models.verf_duration])),
                ('release_date', models.DateField()),
                ('announcement_date', models.DateField()),
                ('has_subtitles', models.BooleanField()),
                ('subtitles_language', models.CharField()),
                ('imdb', models.URLField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, validators=[cinemaapp.models.verf_rating])),
            ],
        ),
    ]
