# Generated by Django 5.2.7 on 2025-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0002_alter_movie_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('SC', 'Sci-Fi'), ('CO', 'Comedy'), ('DR', 'Drama')], max_length=20),
        ),
    ]
